### PR TITLE
Added link to github source on clicking HL logo

### LINKED ISSUE #6: Add link to this github somewhere on site

### PR DESCRIPTION
**Pull request by usselman**
Added link to github source on clicking HL logo, considering there is already a home button on the lower navigation bar.

### CODE REVIEW

**Comment by usselman** [comment]
Good points, happy to take @zer0dt direction on this. Perhaps a floating footer section underneath the bottom navigation bar, could hold github logo and link to 100 lockers chat, twitter link etc

**Comment by zer0dt** [comment]
> Good points, happy to take @zer0dt direction on this. Perhaps a floating footer section underneath the bottom navigation bar, could hold github logo and link to 100 lockers chat, twitter link etc

I'm thinking putting these links on the nav menu when clicking on the avatar on the app / action bar. Would leave display looking clean but links easily accessible.

**Comment by zer0dt** [comment]
Screenshot 2024-01-25 154710

something like this with the Github, Twitter icons (https://react-icons.github.io/react-icons/) in the same row and whatever other links are needed.

**Comment by remjx** [comment]
See https://github.com/zer0dt/hodlocker/pull/19

**Comment by remjx** [comment]
Closing since #19 was merged

**Pull request closed without merging**
